spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blockchain?useUnicode=true&characterEncoding=utf-8&SSL=false
    username: root
    password: 123
  session:
    store-type: none
  security:
    user:
      name: jack
      password: 123
server:
  port: 8080